### PR TITLE
Wip tests for logout controller

### PR DESCRIPTION
**Pull request by EdwardOlmos**
### What this PR does (required):
- Added logout test cases using Mocha and Chai. A simple POST to `/auth/logout` returns a status code of 200 with a text confirming logout and it deletes the token cookie.

### Any information needed to test this feature (required):
- Using the command line, go to the server folder and run the following command: `npm run test`. This will execute the tests provided in this PR.

### Any issues with the current functionality (optional):
- Without adjusting the `app.js` file to include environment variables, I would run into a database connection error. By including the app.js changes, the `npm run test` command works. I'm not sure if there are side effects with this type of change.

### CODE REVIEW

**Comment by ezeilo-su** [comment]
Hey @EdwardOlmos, could you link this ticket, please?

**Review by ezeilo-su — COMMENTED** [review]
Hey @EdwardOlmos, this one is cool.

**Comment by rajivtitus** [comment]
Hey @EdwardOlmos please wait for an approval from a Hatchways team member before you merge a PR :)

**Comment by EdwardOlmos** [comment]
Hey @rajivtitus, my apologies, I went too quick! Should I revert the merge?

**Comment by rajivtitus** [comment]
> Hey @rajivtitus, my apologies, I went too quick! Should I revert the merge?

Hey @EdwardOlmos, don't worry about it. Let's make sure we follow the rule for subsequent PRs

**Pull request merged**
